### ISSUE TITLE
what does "stdout": "${GOLDPLATE_NAME}.stdout" mean

### ISSUE THREAD

**Issue by epogrebnyak** [fugue/goldplate#1]
https://github.com/fugue/goldplate/blob/0e847f753c765e6e6e23fa26aa3b3d8e4b5a21b3/tests/echo.goldplate#L6

It is the first example in the docs, so I dare to ask - what does the variable in the headline contain? Is this example self-fulfilling(any output will be considered valid)?

**Comment by jaspervdj** [comment]
After the environment variables get spliced in, we end up with `{"stdout": "echo.stdout"}`.

This means that we’ll compare the _actual_ output of the program to the contents of the file `echo.stdout`.  You can see that file in the repo as well, filenames are always relative to the `.goldplate` file.

If the two files match, the test succeeds.  You can manually write `echo.stdout` but you can also _generate_ it using `--fix`.  Does that make sense?

**Comment by epogrebnyak** [comment]
It escaped my attention that the test suite has both `*.goldplate` and `*.stdout`. Perhaps I can add some extra wording to the tutorial  as  PR,  hopefully useful to other readers. 

To check:

- we keep reference output in `*.stdout` files 
- we keep test configuration in `*.goldplate` files

But here in specific - the wording is a bit unclear (to me at least):

>We check the stdout (output) of the command against the file ${GOLDPLATE_NAME}.stdout. GOLDPLATE_NAME is the name of the specification without the extension; 

- What prevents us from hard-coding the reference output filename in `echo.goldplate`? Using `${GOLDPLATE_NAME}` must have some advantages?
- What part of syntax is `${GOLDPLATE_NAME}.stdout` - own variable name processor of 
goldplate?
- What does _name of the specification_ mean? Is it name of the specification file, like `echo.goldplate`? Should we call it test specification file or test configuration file or interchangeably?

Many thanks for consideringthe questions, they are probaly obvious to you as developper, but clarification is quite useful to first time user.

**Comment by jaspervdj-luminal** [comment]
Thanks, this is very helpful!  I've simplified a few of the first examples to not use environment variables, and expanded the reference section about environment variables.  I've also avoided the _name of_ nomenclature and now I think the README refers to filenames everywhere.

Do you think it's easier to understand now?  Or maybe you would structure the tutorial differently?  I'm very open to changing things around so they make more sense for first-time users.

**Comment by epogrebnyak** [comment]
I think deferring enviroment variables for later is a good decision. 

I got some editing to the simple assets section, for you to review, feel free to change/discard:

### Simple asserts

View example: [`tests/echo.goldplate`](tests/echo.goldplate)

Imagine we are up to testing the behaviour of `echo` command. In this very simple example, we run `echo "Hello, world!"` and expect it to print `Hello, world!` to stdout stream as a result. 

The test invocation is specified by the `command` and `arguments` fields in [`tests/echo.goldplate`](tests/echo.goldplate).

The expected results of our test live in the `asserts` field.  This simple test has two asserts:

1.  We verify that the exit code is 0 (success).
2.  We check the `stdout` (output) of the command against the file
    [`tests/echo.stdout`](tests/echo.stdout).

```
{
    "command": "echo",
    "arguments": ["Hello, world!"],
    "asserts": [
        {"exit_code": 0},               
        {"stdout": "echo.stdout"}  # <echo.stdout> is a text file with expected output
    ]
}
```
We can check that our asserts are correct with the following call:

    $ goldplate tests/echo.goldplate

**Comment by epogrebnyak** [comment]
Also added a comment for `{"stdout": "echo.stdout"}`, at least in markdown. Upon first glance a reader encounters `"exit_code": 0` and knows it is a value, than one get an expectation "stdout" is also a value, but it is not, and (from the first glance) it is not clear if it is, a filename, so I added a comment. Probably makes more sense after getting used to it.

There are ways to make things a bit more intuitive, but they would be API / naming convention rework, so reporting is just as ideas for consideration:

- `"stdout": "Hello, world!"` vs `"stdout_file": "echo.stdout"` (more work, doubtful)
- `"stdout": "echo.stdout.txt"` - less astonishment, feeling safer `echo.stdout.txt` is a text file - but would complicate the environment variable naming

Really these are probably non-options.

**Comment by jaspervdj-luminal** [comment]
Ok, yeah, that's great, I think I have a much better understanding of what is missing now.  The `stdout` extension is just an extension, one can use whatever they want.  I've chosen `hello-world.txt` for the first example now, since that makes it clear it's just any text file.

I've also rewritten the example to change the perspective from **reading an example** to **writing an example**, since that's more instructive -- I think.

The reason we're using `"stdout_file": "FILE_PATH"` rather than `"stdout": "FILE_CONTENT"` is that it's easier this way to work with external tools, this is something we noticed from experience.  I'll see if I can clarify that as well in the README, but I'm not sure what a good place for that is.

**Comment by epogrebnyak** [comment]
> The reason we're using "stdout_file": "FILE_PATH" rather than "stdout": "FILE_CONTENT" is that it's easier this way to work with external tools, this is something we noticed from experience.

That was my guess, working with files shoud be easier than putting a whole specification into json.

**Comment by epogrebnyak** [comment]
I hate being picky, but maybe quoting patrs of JSON files were is too repetitive and the red dots give a feeling of danger. 

The previous version was quite compact and readable, just like this:

1.    We verify that the exit code is 0 (success).
2.    We check the stdout (output) of the command against the contents of the file `hello-world.txt`.

This part is easy to grasp, for me getting more peices of code distracts readers attention. Sorry ig  I gave a clue to this direction.


```
The expected results of our test live in the asserts field. This simple test has two asserts:

    We verify that the exit code is 0 (success).

    {
        ...
        "asserts": [
            {"exit_code": 0},
            ...
        ]
    }

    We check the stdout (output) of the command against the contents of the file hello-world.txt.

    {
        ...
        "asserts": [
            ...
            {"stdout": "hello-world.txt"}
        ]
    }
```

**Comment by epogrebnyak** [comment]
Two final suggestions:

1. We haven't created hello-world.txt yet, but that's not a problem. (is bold at start intentional? can do without bold)

2. A simplification suggestion:

> The command above creates `hello-world.txt` with the expected output. After verifying the contents of that file, we can check it into our version control system, and we'll know if the output ever changes. 

> After `hello-world.txt` has been created with proper contents, the goldplate invocations will pass:

Let's this piece of docs live its life for a little while - see what other users might sya about it. thank you for developping the tool and your attention to first-time readers.

**Comment by jaspervdj-luminal** [comment]
Those are good suggestions, I applied both of them and also added a more comprehensive list of files used in every example.  Thanks again, I think this will make it much clearer for other people who encounter the tool!

**Comment by epogrebnyak** [comment]
Closing this issue and hope to get be using goldplate for CLIs (`python3 something.py arg1 arg2` should work too, I imagine). Thank you for your time on this!

**Comment by epogrebnyak** [comment]
@jaspervdj-luminal 

```
View example:

    tests/cat.goldplate
    tests/cat.stdout
```

The two files in the example detail appeal exactly to the right intuition!
