### ISSUE TITLE
Integrate `goldplate`'s own tests into the `.cabal` file

### ISSUE THREAD

**Issue by andreasabel** [fugue/goldplate#12]
It would be nice if
```
cabal test
```
ran `goldplate`'s own testsuite.  I suppose this would be easy to implement by adding a suitable `test-suite` stanza to the `.cabal` file.

The benefit would be that users of `goldplate` could easily learn how to integrate `goldplate` into their own `.cabal`-files, by copy-pasting that stanza.

**Comment by andreasabel** [comment]
I am working on a PR to fix this...

**Comment by andreasabel** [comment]
PR #14 is ready.

**Comment by jaspervdj-luminal** [comment]
Fixed in #14.  Thanks again!
