### ISSUE TITLE
Testcase `tests/stdin` not portable

### ISSUE THREAD

**Issue by andreasabel** [fugue/goldplate#13]
```
$ goldplate tests
...
not ok tests/stdin.goldplate: stdout
...
```
https://github.com/fugue/goldplate/blob/91748fa2ac52178cb6c5cee32b8f5a022d5bc759/tests/stdin.stdout#L1

On macOS, `echo -n "hi" | wc -c` outputs some spaces before the letter count:
```
$ echo -n "hi" | wc -c 
       2
$ echo -n "hi" | wc -c | hexdump
0000000 20 20 20 20 20 20 20 32 0a                     
0000009
```

**Comment by jaspervdj-luminal** [comment]
Thanks for reporting!

**Comment by andreasabel** [comment]
Ah, sorry, but this still does not work.
```
$ cat tests/stdin.stdout 
dlrow olleh$ goldplate --fix tests
...
$ cat tests/stdin.stdout 
dlrow olleh
$
```
It seems that macOS-`rev` adds a newline character but linux maybe doesn't...

**Comment by jaspervdj-luminal** [comment]
Ah, that's annoying.  Do you have other suggestions?  I don't have a mac around to test this.

**Comment by andreasabel** [comment]
Maybe `cat` is working uniformly... (see PR #16).
