### ISSUE TITLE
Adding goldplate to stackage

### ISSUE THREAD

**Issue by andreasabel** [fugue/goldplate#15]
@jaspervdj-luminal I'd like goldplate to be in stackage, so I filed https://github.com/commercialhaskell/stackage/pull/6052

There I (implicitly) volunteered as stackage maintainer for goldplate, but I am happy to leave this role to you if you are willing to take it.

**Comment by andreasabel** [comment]
goldplate is part of nightly-2021-06-01! https://www.stackage.org/package/goldplate

**Comment by jaspervdj-luminal** [comment]
Thanks for volunteering!
