### ISSUE TITLE
No warning/error given for malformed `.goldplate` files

### ISSUE THREAD

**Issue by andreasabel** [fugue/goldplate#22]
I accidently put this in my `.goldplate` file:
```json
{ "command"     : "runghc"
, "input_files" : "*.hs"
, "arguments"   : [ "${GOLDPLATE_INPUT_FILE}" ]
, "asserts"     :
  [ { "exit_code" : 0 
    , "stdout"    : "${GOLDPLATE_INPUT_NAME}.golden" 
    }
  ]
}
```
Correct would have been:
```json
, "asserts"     :
  [ { "exit_code" : 0 }
  , { "stdout"    : "${GOLDPLATE_INPUT_NAME}.golden" }
  ]
```
`goldplate` simply ignored the `stdout` part.  I would have preferred an error message alerting me of my mistake.

**Comment by jaspervdj** [comment]
This should be fixed on the current master branch.  Please reopen if that's note the case...
